### ISSUE TITLE
Binary Files are not correctly unpacked

### ISSUE THREAD

**Issue by sirwolfgang** [mxenabled/mx-platform-ruby#90]
I found this working with statements API, but it does effect all file endpoints and as part of the upstream OpenAPI Generator code, effect all file transfers. The header `"content-transfer-encoding"=>"binary"` is never acknowledged making the files functionally corrupt.

The monkey patch to verify this looks something like this
```ruby
# Old
@stream.join.force_encoding(encoding)

# Fixed
@stream.join.unpack('m').join.force_encoding(encoding)
```

**Comment by sirwolfgang** [comment]
I've opened a PR for the patch here: https://github.com/OpenAPITools/openapi-generator/pull/19132

**Comment by sirwolfgang** [comment]
Patch has been merged it, will be available as part of `7.8.0`

**Comment by mogman1** [comment]
Thank you for the report and going the extra mile to submit a patch to the openapi tools generator.  We'll keep an eye out for their next release, but we probably won't be able to pick this up for another week or two (and hopefully by then they'll have pushed out that minor version update).

**Comment by mogman1** [comment]
@sirwolfgang We've released a new version of the SDK using v7.8.0 of the OpenAPITools generator, it's v0.44.1.  Would you mind updating and see if that resolved things as expected?

**Comment by sirwolfgang** [comment]
I just updated to the latest version of the gem and removed my monkey patch, and I still seem to be getting bad PDF files.

**Comment by sirwolfgang** [comment]
I think it needs to be updated to:
```ruby
content = content.unpack('m').join if response.headers['Content-Transfer-Encoding'] == 'binary' && !content.starts_with?('%PDF-')
```

**Comment by sirwolfgang** [comment]
@d4rky-pl The current deployed version is also broken for me, and i've moneypatched in my above line. That is to say, what ever you want to do wont make it more broken for me; please move forward as you see fit.

If you have a snippet, I can try it in my environment and provide feedback to see if it also works for my case.
